services:
  nginx:
    image: nginx
    container_name: nginx
    build: nginx
    ports: ["80:80"]
    restart: unless-stopped
    networks: ["transcendence"]
    depends_on:
      - django
      - parcel
  django:
    image: django
    container_name: django
    build: backend/djangoserv
    restart: unless-stopped
    networks: ["transcendence"]
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
  parcel:
    image: parcel
    container_name: parcel
    build: parcel
    restart: unless-stopped
    networks: ["transcendence"]
  postgres:
    image: postgres
    container_name: postgres
    build: postgres
    restart: unless-stopped
    networks: ["transcendence"]
    env_file: .env
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]

networks:
  transcendence:
