services:
  nginx:
    image: nginx
    container_name: nginx
    build: nginx
    ports: ["80:80"]
    restart: unless-stopped
    networks: ["transcendence"]
  django:
    image: django
    container_name: django
    build: backend/djangoserv
    restart: unless-stopped
    networks: ["transcendence"]
    env_file: .env
  parcel:
    image: parcel
    container_name: parcel
    build: parcel
    restart: unless-stopped
    networks: ["transcendence"]

networks:
  transcendence:
