services:
  nginx:
    image: nginx
    container_name: nginx
    build: nginx
    ports: ["443:443"]
    restart: unless-stopped
    secrets:
      - certificate.crt
      - certificate.key
    networks: 
      - transcendence
      - monitoring
    volumes:
      - nginx-logs:/var/log/nginx
    depends_on:
      - django
      - elasticsearch
      - kibana
      - grafana
#      - parcel

  django:
    image: django
    container_name: django
    build: backend/djangoserv
    restart: unless-stopped
    networks: ["transcendence"]
    env_file: .env
    volumes:
      - django-logs:/djangologs/
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    container_name: postgres
    build: postgres
    restart: unless-stopped
    networks: ["transcendence"]
    env_file: .env
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      retries: 30

  prometheus:
    build:
      context: .
      dockerfile: ./monitoring/prometheus/Dockerfile
    container_name: prometheus
    volumes:
      - prometheus-storage:/prometheus-data
    restart: unless-stopped
    networks: ["monitoring"]

  grafana:
    build:
      context: .
      dockerfile: ./monitoring/grafana/Dockerfile
    container_name: grafana
    env_file:
      - .env
    volumes:
      - grafana-logs:/grafana/data/log
      - grafana-storage:/var/lib/grafana
    depends_on:
      prometheus:
        condition: service_healthy
    restart: unless-stopped
    networks: ["monitoring"]

  node-exporter:
    build:
      context: .
      dockerfile: ./monitoring/node-exporter/Dockerfile
    container_name: node-exporter
    depends_on:
      prometheus:
        condition: service_healthy
    restart: unless-stopped
    networks: ["monitoring"]

  alertmanager:
    build:
      context: .
      dockerfile: ./monitoring/alertmanager/Dockerfile
    container_name: alertmanager
    env_file:
      - .env
    depends_on:
      prometheus:
        condition: service_healthy
    restart: unless-stopped
    networks: ["monitoring"]

  elasticsearch:
    build: ./logging/elasticsearch
    container_name: elasticsearch
    env_file: .env
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - http.cors.allow-origin=*
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - es-logs:/usr/share/elasticsearch/logs
    restart: unless-stopped
    networks: ["monitoring"]

  logstash:
    build: ./logging/logstash
    container_name: logstash
    volumes:
      - logstash-logs:/usr/share/logstash/logs
    restart: unless-stopped
    env_file: .env
    networks: ["monitoring"]
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: ./logging/kibana
      args:
        KIBANA_SYSTEM_USERNAME: ${KIBANA_SYSTEM_USERNAME}
        ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
        XPACK_SECURITY_ENCRYPTIONKEY: ${XPACK_SECURITY_ENCRYPTIONKEY}
        XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: ${XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY}
        XPACK_REPORTING_ENCRYPTIONKEY: ${XPACK_REPORTING_ENCRYPTIONKEY}
    container_name: kibana
    volumes:
      - kibana-logs:/kibanalog/
    restart: unless-stopped
    env_file: .env
    networks: ["monitoring"]
    depends_on:
      - elasticsearch

  filebeat:
    build: ./logging/filebeat
    container_name: filebeat
    user: root
    volumes:
      - nginx-logs:/var/log/nginx:ro
      - django-logs:/djangologs:ro
      - es-logs:/usr/share/elasticsearch/logs:ro
      - logstash-logs:/usr/share/logstash/logs:ro
      - kibana-logs:/kibanalog:ro
      - grafana-logs:/grafana/data/log:ro
    restart: unless-stopped
    networks: ["monitoring"]
    depends_on:
      - logstash

networks:
  transcendence:
  monitoring:

volumes:
  grafana-storage:
  prometheus-storage:
  esdata:
  nginx-logs:
  django-logs:
  es-logs:
  logstash-logs:
  kibana-logs:
  grafana-logs:
  elk-volume:

secrets:
  certificate.crt:
    file: certificate.crt
  certificate.key:
    file: certificate.key
