name: filebeat

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

# Input for Docker JSON logs
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/lib/docker/containers/*/*.log
  json.keys_under_root: true
  json.add_error_key: true
  processors:
    - add_docker_metadata: ~

# Input for other non-JSON logs
- type: log
  enabled: true
  paths:
    - /var/log/nginx/*.log
    - /djangologs/*.log
    - /usr/share/elasticsearch/logs/*.log
    - /usr/share/logstash/logs/*.log
    - /kibanalog/*.log
    - /grafana/data/log/*.log

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config:
        type: container
        paths:
          - /var/lib/docker/containers/${data.container.id}/*-json.log
      templates:
        - condition:
            contains:
              docker.container.image: elasticsearch
          config:
            - module: elasticsearch
              server:
                input:
                  type: container
                  paths:
                    - /var/lib/docker/containers/${data.container.id}/*-json.log

processors:
  - add_cloud_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]

## HTTP endpoint for health checking
http:
  enabled: true
  host: 0.0.0.0
